#!/bin/bash
# Copyright (c) 2019-2020 Tom Hancocks
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

DIR=$(pwd)
ORIG_DIR=$(pwd)

if [[ "${DIR}" =~ Support/Tools/$ ]]; then
	DIR=$(echo ${DIR} | rev | cut -d '/' -f4- | rev)
elif [[ "${DIR}" =~ Support/Tools$ ]]; then
	DIR=$(echo ${DIR} | rev | cut -d '/' -f3- | rev)
fi

# Create an intermediate directories in ./bin
if [[ "$(uname -s)" == "Darwin" ]]; then
	OS="macOS"
	INSTALLER="Installer-macOS.kdl"
elif [[ "$(uname -s)" == "Linux" ]]; then
	OS="Linux"
	INSTALLER="Installer-macOS.kdl" # Use the macOS installer package for now.
else
	echo "Unable to construct release package."
	exit 1
fi

rm -rf "${DIR}/bin/${OS}" "${DIR}/cmake-build-debug"
mkdir -p "${DIR}/bin/${OS}"
mkdir -p "${DIR}/cmake-build-debug"

# Trigger a build of KDL, and copy in the resulting binary
cmake -B "${DIR}/cmake-build-debug"
cmake --build "${DIR}/cmake-build-debug" -- -j3
cp "${DIR}/bin/kdl" "${DIR}/bin/${OS}/kdl"

# Build the installer package - make sure to use the newly build KDL!!
KDL="${DIR}/bin/kdl"
${KDL} -o "${DIR}/bin/${OS}/InstallationData" "${DIR}/Support/Installer/${INSTALLER}"

# Create README
cp "${DIR}/Support/Installer/Read Me.txt" "${DIR}/bin/${OS}/Read Me.txt"

# Create Installer
cat <<EOF >> "${DIR}/bin/${OS}/Install"
#!/bin/sh

DIR=\$(dirname "\${BASH_SOURCE[0]}")
cd "\${DIR}"

./kdl --install InstallationData.kdl

echo "Please ensure that you have /usr/local/bin in your \$PATH in order to use KDL"
EOF
chmod 0755 "${DIR}/bin/${OS}/Install"

# Package as Zip Archive for distribution
VERSION=$(git describe --tags --dirty --match "v*")
cd "${DIR}/bin"
zip -r "${DIR}/bin/KDL-${VERSION}-${OS}.zip" "${OS}"
cd "${ORIG_DIR}"