#!/bin/bash
# Copyright (c) 2019-2020 Tom Hancocks
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

DIR=$(pwd)

if [[ "${DIR}" =~ Support/Tools/$ ]]; then
	DIR=$(echo ${DIR} | rev | cut -d '/' -f4- | rev)
elif [[ "${DIR}" =~ Support/Tools$ ]]; then
	DIR=$(echo ${DIR} | rev | cut -d '/' -f3- | rev)
fi

# Create an intermediate directories in ./bin
if [[ "$(uname -s)" == "Darwin" ]]; then
	OS="macOS"
elif [[ "$(uname -s)" == "Linux" ]]; then
	OS="Linux"
else
	echo "Unable to construct release package."
	exit 1
fi

rm -rf "${DIR}/bin/${OS}" "${DIR}/cmake-build-debug"
mkdir -p "${DIR}/bin/${OS}/data/evn/Types"
mkdir -p "${DIR}/cmake-build-debug"

# Trigger a build of KDL, and copy in the resulting binary
cmake -B "${DIR}/cmake-build-debug"
cmake --build "${DIR}/cmake-build-debug" -- -j3
cp "${DIR}/bin/kdl" "${DIR}/bin/${OS}/kdl"

# Check out the KDL-Nova repository.
if [[ -d "/tmp/kdl-nova" ]]; then
	git --git-dir=/tmp/kdl-nova/.git --work-tree=/tmp/kdl-nova pull
else
	git clone git@github.com:tjhancocks/kdl-nova.git /tmp/kdl-nova
fi
cp -v /tmp/kdl-nova/Manifest.kdl "${DIR}/bin/${OS}/data/evn/Manifest.kdl"
cp -v /tmp/kdl-nova/Types/*.kdl "${DIR}/bin/${OS}/data/evn/Types/"

# Setup a default configuration file for KDL
cp -v "${DIR}/Support/example.config.kdl" "${DIR}/bin/${OS}/default.config.kdl"

# Produce an installer script.
cat <<EOF >> "${DIR}/bin/${OS}/Install"
#!/bin/sh
# Automatically Generated
DIR=\$(dirname "\${BASH_SOURCE[0]}")
cd "\${DIR}"

rm "/usr/local/bin/kdl"
cp "\${DIR}/kdl" "/usr/local/bin/kdl"

if [[ ! -f "\${HOME}/.config.kdl" ]]; then
	cp "\${DIR}/default.config.kdl" "\${HOME}/.config.kdl"
fi

if [[ ! -d "\${HOME}/.kdl" ]]; then
	mkdir -p "\${HOME}/.kdl"
fi

cp -rf "\${DIR}/data/evn" "\${HOME}/.kdl"

echo "You need to make sure that /usr/local/bin is in your PATH"
EOF
chmod 0755 "${DIR}/bin/${OS}/Install"

# Create a zip archive
VERSION=$(git describe --tags --dirty --match "v*")
zip -r "${DIR}/bin/KDL-${VERSION}-${OS}.zip" "${DIR}/bin/${OS}"